code

equ	trap_LocateGameData		            -1
equ	trap_DropClient			            -2
equ	trap_SendServerCommand	            -3
equ	trap_LinkEntity			            -4
equ	trap_UnlinkEntity		            -5
equ	trap_EntitiesInBox		            -6
equ	trap_EntityContact		            -7
equ	trap_Trace				            -8
equ	trap_PointContents		            -9
equ	trap_SetBrushModel		            -10
equ trap_InPVS				            -11
equ	trap_SetConfigstring	            -12
equ	trap_GetConfigstring	            -13
equ	trap_SetUserinfo		            -14
equ	trap_GetUserinfo		            -15
equ	trap_GetServerinfo		            -16
equ	trap_AdjustAreaPortalState	        -17
equ	trap_BotAllocateClient	            -18
equ	trap_GetUsercmd			            -19
equ	trap_GetEntityToken		            -20

equ trap_BotLibSetup					-2001
equ trap_BotLibShutdown					-2002
equ trap_BotLibStartFrame				-2003
equ trap_BotLibLoadMap					-2004
equ trap_BotLibUpdateEntity				-2005
equ trap_BotGetServerCommand		    -2006
equ trap_BotUserCommand					-2007
equ trap_AAS_EntityInfo					-2008
equ trap_AAS_Initialized				-2009
equ trap_AAS_Time						-2010
equ trap_AAS_PointAreaNum				-2011
equ trap_AAS_TraceAreas					-2012
equ trap_EA_Command						-2013
equ trap_EA_Gesture						-2014
equ trap_EA_Attack						-2015
equ trap_EA_Use							-2016
equ trap_EA_SelectWeapon				-2017
equ trap_EA_View						-2018
equ trap_EA_GetInput					-2019
equ trap_EA_ResetInput					-2020
equ trap_BotTouchingGoal				-2021
equ trap_BotMoveToGoal					-2022
equ trap_BotResetMoveState				-2023
equ trap_BotAllocMoveState				-2024
equ trap_BotFreeMoveState				-2025
equ trap_BotInitMoveState				-2026
