// Copyright (C) 1999-2005 ID Software, Inc.
// Copyright (C) 2023-2025 Noire.dev
// Copyright (C) 2025 OpenSandbox Team
// OpenSandbox — GPLv2; see LICENSE for details.

#define INVENTORY_NONE				0
//armor
#define INVENTORY_ARMOR				1
//powerups
#define INVENTORY_HEALTH			2
#define INVENTORY_TELEPORTER		3
#define INVENTORY_MEDKIT			4
#define INVENTORY_KAMIKAZE			5
#define INVENTORY_PORTAL			6
#define INVENTORY_INVULNERABILITY	7
#define INVENTORY_QUAD			    8
#define INVENTORY_ENVIRONMENTSUIT	9
#define INVENTORY_HASTE				10
#define INVENTORY_INVISIBILITY		11
#define INVENTORY_REGEN				12
#define INVENTORY_FLIGHT			13
#define INVENTORY_SCOUT				14
#define INVENTORY_GUARD				15
#define INVENTORY_DOUBLER			16
#define INVENTORY_AMMOREGEN			17
//team
#define INVENTORY_REDFLAG			18
#define INVENTORY_BLUEFLAG			19
#define INVENTORY_NEUTRALFLAG		20
#define INVENTORY_REDCUBE			21
#define INVENTORY_BLUECUBE			22
//general
#define INVENTORY_GENERAL    		23

//enemy stuff
#define ENEMY_HORIZONTAL_DIST		200
#define ENEMY_HEIGHT				201
#define NUM_VISIBLE_ENEMIES			202
#define NUM_VISIBLE_TEAMMATES		203

//item numbers (make sure they are in sync with gameInfoItems in bg_misc.c)
#define MODELINDEX_ARMORSHARD		1
#define MODELINDEX_ARMORCOMBAT		2
#define MODELINDEX_ARMORBODY		3
#define MODELINDEX_HEALTHSMALL		4
#define MODELINDEX_HEALTH			5
#define MODELINDEX_HEALTHLARGE		6
#define MODELINDEX_HEALTHMEGA		7
#define MODELINDEX_GAUNTLET			8
#define MODELINDEX_MACHINEGUN		9
#define MODELINDEX_SHOTGUN			10
#define MODELINDEX_GRENADELAUNCHER	11
#define MODELINDEX_ROCKETLAUNCHER	12
#define MODELINDEX_LIGHTNING		13
#define MODELINDEX_RAILGUN			14
#define MODELINDEX_PLASMAGUN		15
#define MODELINDEX_BFG10K			16
#define MODELINDEX_GRAPPLINGHOOK	17
#define MODELINDEX_NAILGUN			18
#define MODELINDEX_PROXLAUNCHER		19
#define MODELINDEX_CHAINGUN			20
#define MODELINDEX_FLAMETHROWER		21
#define MODELINDEX_ANTIMATTER		22
#define MODELINDEX_PHYSGUN		    23
#define MODELINDEX_GRAVITYGUN		24
#define MODELINDEX_TOOLGUN		    25
#define MODELINDEX_THROWER		    26
#define MODELINDEX_BOUNCER		    27
#define MODELINDEX_THUNDER		    28
#define MODELINDEX_EXPLODER		    29
#define MODELINDEX_KNOCKER		    30
#define MODELINDEX_PROPGUN		    31
#define MODELINDEX_REGENERATOR		32
#define MODELINDEX_NUKE		        33
#define MODELINDEX_BULLETS			34
#define MODELINDEX_SHELLS			35
#define MODELINDEX_GRENADES			36
#define MODELINDEX_CELLS			37
#define MODELINDEX_LIGHTNINGAMMO	38
#define MODELINDEX_ROCKETS			39
#define MODELINDEX_SLUGS			40
#define MODELINDEX_BFGAMMO			41
#define MODELINDEX_NAILS			42
#define MODELINDEX_MINES			43
#define MODELINDEX_BELT				44
#define MODELINDEX_TELEPORTER		45
#define MODELINDEX_MEDKIT			46
#define MODELINDEX_KAMIKAZE			47
#define MODELINDEX_PORTAL			48
#define MODELINDEX_INVULNERABILITY	49
#define MODELINDEX_QUAD				50
#define MODELINDEX_ENVIRONMENTSUIT	51
#define MODELINDEX_HASTE			52
#define MODELINDEX_INVISIBILITY		53
#define MODELINDEX_REGEN			54
#define MODELINDEX_FLIGHT			55
#define MODELINDEX_SCOUT			56
#define MODELINDEX_GUARD			57
#define MODELINDEX_DOUBLER			58
#define MODELINDEX_AMMOREGEN		59
#define MODELINDEX_REDFLAG			60
#define MODELINDEX_BLUEFLAG			61
#define MODELINDEX_NEUTRALFLAG		62
#define MODELINDEX_REDCUBE			63
#define MODELINDEX_BLUECUBE			64
