code

equ	trap_Error								-1
equ	trap_Print								-2
equ	trap_Milliseconds						-3
equ	trap_Cvar_Set							-4
equ	trap_Cvar_VariableValue					-5
equ	trap_Cvar_VariableStringBuffer			-6
equ	trap_Cvar_SetValue						-7
equ	trap_Cvar_Reset							-8
equ	trap_Argc								-9
equ	trap_Argv								-10
equ	trap_Cmd_ExecuteText					-11
equ	trap_FS_FOpenFile						-12
equ	trap_FS_Read							-13
equ	trap_FS_Write							-14
equ	trap_FS_FCloseFile						-15
equ	trap_FS_GetFileList						-16
equ	trap_R_RegisterModel					-17
equ	trap_R_RegisterSkin						-18
equ	trap_R_RegisterShaderNoMip				-19
equ	trap_R_ClearScene						-20
equ	trap_R_AddRefEntityToScene				-21
equ	trap_R_AddPolyToScene					-22
equ	trap_R_AddLightToScene					-23
equ	trap_R_RenderScene						-24
equ	trap_R_SetColor							-25
equ	trap_R_DrawStretchPic					-26
equ	trap_UpdateScreen						-27
equ	trap_CM_LerpTag							-28
equ	trap_S_RegisterSound					-29
equ	trap_S_StartLocalSound					-30
equ	trap_Key_KeynumToStringBuf				-31
equ	trap_Key_GetBindingBuf					-32
equ	trap_Key_SetBinding						-33
equ	trap_Key_IsDown							-34
equ	trap_Key_GetOverstrikeMode				-35
equ	trap_Key_SetOverstrikeMode				-36
equ	trap_Key_ClearStates					-37
equ	trap_Key_GetCatcher						-38
equ	trap_Key_SetCatcher						-39
equ	trap_GetClipboardData					-40
equ	trap_GetGlconfig						-41
equ	trap_GetClientState						-42
equ	trap_GetConfigString					-43
equ	trap_LAN_GetPingQueueCount				-44
equ	trap_LAN_ClearPing						-45
equ	trap_LAN_GetPing						-46
equ	trap_LAN_GetPingInfo					-47
equ	trap_Cvar_Register						-48
equ trap_Cvar_Update						-49
equ trap_MemoryRemaining					-50
equ trap_RealTime							-51
equ trap_LAN_GetServerCount					-52
equ trap_LAN_GetServerAddressString			-53
equ trap_R_RemapShader						-54
equ trap_System 		                    -55

equ	memset						-101
equ	memcpy						-102
equ	strncpy						-103
equ	sin							-104
equ	cos							-105
equ	atan2						-106
equ	sqrt						-107
equ floor						-108
equ	ceil						-109
