code

equ	trap_Print							-1
equ	trap_Error							-2
equ	trap_Milliseconds					-3
equ	trap_Cvar_Register					-4
equ	trap_Cvar_Update					-5
equ	trap_Cvar_Set						-6
equ trap_Cvar_VariableStringBuffer		-7
equ	trap_Argc							-8
equ	trap_Argv							-9
equ	trap_Args							-10
equ	trap_FS_FOpenFile					-11
equ	trap_FS_Read						-12
equ	trap_FS_Write						-13
equ	trap_FS_FCloseFile					-14
equ	trap_SendConsoleCommand				-15
equ	trap_AddCommand						-16
equ	trap_SendClientCommand				-17
equ	trap_UpdateScreen					-18
equ	trap_CM_LoadMap						-19
equ	trap_CM_NumInlineModels				-20
equ	trap_CM_InlineModel					-21
equ	trap_CM_TempBoxModel				-22
equ	trap_CM_PointContents				-23
equ	trap_CM_TransformedPointContents	-24
equ	trap_CM_BoxTrace					-25
equ	trap_CM_TransformedBoxTrace			-26
equ	trap_CM_MarkFragments				-27
equ	trap_S_StartSound					-28
equ	trap_S_StartLocalSound				-29
equ	trap_S_ClearLoopingSounds			-30
equ	trap_S_AddLoopingSound				-31
equ	trap_S_UpdateEntityPosition			-32
equ	trap_S_Respatialize					-33
equ	trap_S_RegisterSound				-34
equ	trap_S_StartBackgroundTrack			-35
equ	trap_R_LoadWorldMap					-36
equ	trap_R_RegisterModel				-37
equ	trap_R_RegisterSkin					-38
equ	trap_R_RegisterShader				-39
equ	trap_R_ClearScene					-40
equ	trap_R_AddRefEntityToScene			-41
equ	trap_R_AddPolyToScene				-42
equ	trap_R_AddLightToScene				-43
equ	trap_R_RenderScene					-44
equ	trap_R_SetColor						-45
equ	trap_R_DrawStretchPic				-46
equ	trap_R_ModelBounds					-47
equ	trap_R_LerpTag						-48
equ	trap_GetGlconfig					-49
equ	trap_GetGameState					-50
equ	trap_GetCurrentSnapshotNumber		-51
equ	trap_GetSnapshot					-52
equ	trap_GetServerCommand				-53
equ	trap_GetCurrentCmdNumber			-54
equ	trap_GetUserCmd						-55
equ	trap_SetUserCmdValue				-56
equ	trap_R_RegisterShaderNoMip			-57
equ trap_Key_GetCatcher					-58
equ trap_Key_GetKey						-59
equ trap_RealTime						-60
equ trap_R_RemapShader					-61
equ	trap_S_AddRealLoopingSound			-62
equ trap_S_StopLoopingSound				-63
equ trap_System				            -64
equ trap_R_AddLinearLightToScene		-65

equ	memset						        -101
equ	memcpy						        -102
equ	strncpy						        -103
equ	sin							        -104
equ	cos							        -105
equ	atan2						        -106
equ	sqrt						        -107
equ acos						        -108
